export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
import "bootstrap/dist/css/bootstrap.css";
import "./globals.css";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <h1>Header</h1>
        {children}
        <h1>Footer</h1>
      </body>
    </html>
  );
}
